// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: decision/claim.proto

package decision

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimType int32

const (
	ClaimType_unspecified ClaimType = 0
	ClaimType_choice      ClaimType = 1
	ClaimType_score       ClaimType = 2
	ClaimType_noul        ClaimType = 3
)

// Enum value maps for ClaimType.
var (
	ClaimType_name = map[int32]string{
		0: "unspecified",
		1: "choice",
		2: "score",
		3: "noul",
	}
	ClaimType_value = map[string]int32{
		"unspecified": 0,
		"choice":      1,
		"score":       2,
		"noul":        3,
	}
)

func (x ClaimType) Enum() *ClaimType {
	p := new(ClaimType)
	*p = x
	return p
}

func (x ClaimType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimType) Descriptor() protoreflect.EnumDescriptor {
	return file_decision_claim_proto_enumTypes[0].Descriptor()
}

func (ClaimType) Type() protoreflect.EnumType {
	return &file_decision_claim_proto_enumTypes[0]
}

func (x ClaimType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimType.Descriptor instead.
func (ClaimType) EnumDescriptor() ([]byte, []int) {
	return file_decision_claim_proto_rawDescGZIP(), []int{0}
}

// One semantic judgment. Context contains facts, constraints and option meanings.
type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ClaimType              `protobuf:"varint,1,opt,name=type,proto3,enum=decision.ClaimType" json:"type,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_decision_claim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_decision_claim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_decision_claim_proto_rawDescGZIP(), []int{0}
}

func (x *Claim) GetType() ClaimType {
	if x != nil {
		return x.Type
	}
	return ClaimType_unspecified
}

func (x *Claim) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Claim) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Evaluation metadata; exactly one value matches the Claim's type.
type Evaluation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Evaluation_Choice
	//	*Evaluation_Score
	//	*Evaluation_Noul
	Value         isEvaluation_Value `protobuf_oneof:"value"`
	Probabilities map[string]float64 `protobuf:"bytes,4,rep,name=probabilities,proto3" json:"probabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Confidence    float64            `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evaluation) Reset() {
	*x = Evaluation{}
	mi := &file_decision_claim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evaluation) ProtoMessage() {}

func (x *Evaluation) ProtoReflect() protoreflect.Message {
	mi := &file_decision_claim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evaluation.ProtoReflect.Descriptor instead.
func (*Evaluation) Descriptor() ([]byte, []int) {
	return file_decision_claim_proto_rawDescGZIP(), []int{1}
}

func (x *Evaluation) GetValue() isEvaluation_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Evaluation) GetChoice() string {
	if x != nil {
		if x, ok := x.Value.(*Evaluation_Choice); ok {
			return x.Choice
		}
	}
	return ""
}

func (x *Evaluation) GetScore() float64 {
	if x != nil {
		if x, ok := x.Value.(*Evaluation_Score); ok {
			return x.Score
		}
	}
	return 0
}

func (x *Evaluation) GetNoul() float64 {
	if x != nil {
		if x, ok := x.Value.(*Evaluation_Noul); ok {
			return x.Noul
		}
	}
	return 0
}

func (x *Evaluation) GetProbabilities() map[string]float64 {
	if x != nil {
		return x.Probabilities
	}
	return nil
}

func (x *Evaluation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type isEvaluation_Value interface {
	isEvaluation_Value()
}

type Evaluation_Choice struct {
	Choice string `protobuf:"bytes,1,opt,name=choice,proto3,oneof"`
}

type Evaluation_Score struct {
	Score float64 `protobuf:"fixed64,2,opt,name=score,proto3,oneof"`
}

type Evaluation_Noul struct {
	Noul float64 `protobuf:"fixed64,3,opt,name=noul,proto3,oneof"`
}

func (*Evaluation_Choice) isEvaluation_Value() {}

func (*Evaluation_Score) isEvaluation_Value() {}

func (*Evaluation_Noul) isEvaluation_Value() {}

var File_decision_claim_proto protoreflect.FileDescriptor

const file_decision_claim_proto_rawDesc = "" +
	"\n" +
	"\x14decision/claim.proto\x12\bdecision\"d\n" +
	"\x05Claim\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.decision.ClaimTypeR\x04type\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\"\x8e\x02\n" +
	"\n" +
	"Evaluation\x12\x18\n" +
	"\x06choice\x18\x01 \x01(\tH\x00R\x06choice\x12\x16\n" +
	"\x05score\x18\x02 \x01(\x01H\x00R\x05score\x12\x14\n" +
	"\x04noul\x18\x03 \x01(\x01H\x00R\x04noul\x12M\n" +
	"\rprobabilities\x18\x04 \x03(\v2'.decision.Evaluation.ProbabilitiesEntryR\rprobabilities\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x1a@\n" +
	"\x12ProbabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B\a\n" +
	"\x05value*=\n" +
	"\tClaimType\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\n" +
	"\n" +
	"\x06choice\x10\x01\x12\t\n" +
	"\x05score\x10\x02\x12\b\n" +
	"\x04noul\x10\x03B7Z5github.com/chainreactors/cyber/core/decision;decisionb\x06proto3"

var (
	file_decision_claim_proto_rawDescOnce sync.Once
	file_decision_claim_proto_rawDescData []byte
)

func file_decision_claim_proto_rawDescGZIP() []byte {
	file_decision_claim_proto_rawDescOnce.Do(func() {
		file_decision_claim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decision_claim_proto_rawDesc), len(file_decision_claim_proto_rawDesc)))
	})
	return file_decision_claim_proto_rawDescData
}

var file_decision_claim_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_decision_claim_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_decision_claim_proto_goTypes = []any{
	(ClaimType)(0),     // 0: decision.ClaimType
	(*Claim)(nil),      // 1: decision.Claim
	(*Evaluation)(nil), // 2: decision.Evaluation
	nil,                // 3: decision.Evaluation.ProbabilitiesEntry
}
var file_decision_claim_proto_depIdxs = []int32{
	0, // 0: decision.Claim.type:type_name -> decision.ClaimType
	3, // 1: decision.Evaluation.probabilities:type_name -> decision.Evaluation.ProbabilitiesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_decision_claim_proto_init() }
func file_decision_claim_proto_init() {
	if File_decision_claim_proto != nil {
		return
	}
	file_decision_claim_proto_msgTypes[1].OneofWrappers = []any{
		(*Evaluation_Choice)(nil),
		(*Evaluation_Score)(nil),
		(*Evaluation_Noul)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decision_claim_proto_rawDesc), len(file_decision_claim_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_decision_claim_proto_goTypes,
		DependencyIndexes: file_decision_claim_proto_depIdxs,
		EnumInfos:         file_decision_claim_proto_enumTypes,
		MessageInfos:      file_decision_claim_proto_msgTypes,
	}.Build()
	File_decision_claim_proto = out.File
	file_decision_claim_proto_goTypes = nil
	file_decision_claim_proto_depIdxs = nil
}
