// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: types/guardrail.proto

package guardrail

import (
	aop "github.com/chainreactors/cyber/aop"
	operation "github.com/chainreactors/cyber/aop/operation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_RECORD      Action = 1
	Action_ACTION_REVIEW      Action = 2
	Action_ACTION_BLOCK       Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_RECORD",
		2: "ACTION_REVIEW",
		3: "ACTION_BLOCK",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_RECORD":      1,
		"ACTION_REVIEW":      2,
		"ACTION_BLOCK":       3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_types_guardrail_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_types_guardrail_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{0}
}

type ReviewState int32

const (
	ReviewState_REVIEW_STATE_UNSPECIFIED ReviewState = 0
	ReviewState_REVIEW_STATE_PENDING     ReviewState = 1
	ReviewState_REVIEW_STATE_APPROVED    ReviewState = 2
	ReviewState_REVIEW_STATE_REJECTED    ReviewState = 3
	ReviewState_REVIEW_STATE_EXPIRED     ReviewState = 4
	ReviewState_REVIEW_STATE_CANCELED    ReviewState = 5
)

// Enum value maps for ReviewState.
var (
	ReviewState_name = map[int32]string{
		0: "REVIEW_STATE_UNSPECIFIED",
		1: "REVIEW_STATE_PENDING",
		2: "REVIEW_STATE_APPROVED",
		3: "REVIEW_STATE_REJECTED",
		4: "REVIEW_STATE_EXPIRED",
		5: "REVIEW_STATE_CANCELED",
	}
	ReviewState_value = map[string]int32{
		"REVIEW_STATE_UNSPECIFIED": 0,
		"REVIEW_STATE_PENDING":     1,
		"REVIEW_STATE_APPROVED":    2,
		"REVIEW_STATE_REJECTED":    3,
		"REVIEW_STATE_EXPIRED":     4,
		"REVIEW_STATE_CANCELED":    5,
	}
)

func (x ReviewState) Enum() *ReviewState {
	p := new(ReviewState)
	*p = x
	return p
}

func (x ReviewState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewState) Descriptor() protoreflect.EnumDescriptor {
	return file_types_guardrail_proto_enumTypes[1].Descriptor()
}

func (ReviewState) Type() protoreflect.EnumType {
	return &file_types_guardrail_proto_enumTypes[1]
}

func (x ReviewState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewState.Descriptor instead.
func (ReviewState) EnumDescriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{1}
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=cyber.guardrail.Action" json:"action,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_types_guardrail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_types_guardrail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{0}
}

func (x *Decision) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Review struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Call      *aop.ToolCall          `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	Operation *operation.Ref         `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Decision  *Decision              `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	State     ReviewState            `protobuf:"varint,5,opt,name=state,proto3,enum=cyber.guardrail.ReviewState" json:"state,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Trusted resolving adapter, not an asserted user identity. Empty for older records.
	ResolutionSource string `protobuf:"bytes,7,opt,name=resolution_source,json=resolutionSource,proto3" json:"resolution_source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_types_guardrail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_types_guardrail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{1}
}

func (x *Review) GetCall() *aop.ToolCall {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *Review) GetOperation() *operation.Ref {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Review) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Review) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *Review) GetState() ReviewState {
	if x != nil {
		return x.State
	}
	return ReviewState_REVIEW_STATE_UNSPECIFIED
}

func (x *Review) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Review) GetResolutionSource() string {
	if x != nil {
		return x.ResolutionSource
	}
	return ""
}

type PendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRequest) Reset() {
	*x = PendingRequest{}
	mi := &file_types_guardrail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRequest) ProtoMessage() {}

func (x *PendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_guardrail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRequest.ProtoReflect.Descriptor instead.
func (*PendingRequest) Descriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{2}
}

func (x *PendingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingResponse) Reset() {
	*x = PendingResponse{}
	mi := &file_types_guardrail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingResponse) ProtoMessage() {}

func (x *PendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_guardrail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingResponse.ProtoReflect.Descriptor instead.
func (*PendingResponse) Descriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{3}
}

func (x *PendingResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_types_guardrail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_guardrail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResolveRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ResolveRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_types_guardrail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_guardrail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{5}
}

type ProtocolMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ProtocolMessage_Pending
	//	*ProtocolMessage_PendingResult
	//	*ProtocolMessage_Resolve
	//	*ProtocolMessage_Resolved
	Message       isProtocolMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessage) Reset() {
	*x = ProtocolMessage{}
	mi := &file_types_guardrail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessage) ProtoMessage() {}

func (x *ProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_guardrail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessage.ProtoReflect.Descriptor instead.
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return file_types_guardrail_proto_rawDescGZIP(), []int{6}
}

func (x *ProtocolMessage) GetMessage() isProtocolMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProtocolMessage) GetPending() *PendingRequest {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Pending); ok {
			return x.Pending
		}
	}
	return nil
}

func (x *ProtocolMessage) GetPendingResult() *PendingResponse {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_PendingResult); ok {
			return x.PendingResult
		}
	}
	return nil
}

func (x *ProtocolMessage) GetResolve() *ResolveRequest {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Resolve); ok {
			return x.Resolve
		}
	}
	return nil
}

func (x *ProtocolMessage) GetResolved() *ResolveResponse {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Resolved); ok {
			return x.Resolved
		}
	}
	return nil
}

type isProtocolMessage_Message interface {
	isProtocolMessage_Message()
}

type ProtocolMessage_Pending struct {
	Pending *PendingRequest `protobuf:"bytes,1,opt,name=pending,proto3,oneof"`
}

type ProtocolMessage_PendingResult struct {
	PendingResult *PendingResponse `protobuf:"bytes,2,opt,name=pending_result,json=pendingResult,proto3,oneof"`
}

type ProtocolMessage_Resolve struct {
	Resolve *ResolveRequest `protobuf:"bytes,3,opt,name=resolve,proto3,oneof"`
}

type ProtocolMessage_Resolved struct {
	Resolved *ResolveResponse `protobuf:"bytes,4,opt,name=resolved,proto3,oneof"`
}

func (*ProtocolMessage_Pending) isProtocolMessage_Message() {}

func (*ProtocolMessage_PendingResult) isProtocolMessage_Message() {}

func (*ProtocolMessage_Resolve) isProtocolMessage_Message() {}

func (*ProtocolMessage_Resolved) isProtocolMessage_Message() {}

var File_types_guardrail_proto protoreflect.FileDescriptor

const file_types_guardrail_proto_rawDesc = "" +
	"\n" +
	"\x15types/guardrail.proto\x12\x0fcyber.guardrail\x1a\x11aop/content.proto\x1a\x1caop/operation/protocol.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\bDecision\x12/\n" +
	"\x06action\x18\x01 \x01(\x0e2\x17.cyber.guardrail.ActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xcf\x02\n" +
	"\x06Review\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.aop.ToolCallR\x04call\x120\n" +
	"\toperation\x18\x02 \x01(\v2\x12.aop.operation.RefR\toperation\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x125\n" +
	"\bdecision\x18\x04 \x01(\v2\x19.cyber.guardrail.DecisionR\bdecision\x122\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1c.cyber.guardrail.ReviewStateR\x05state\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12+\n" +
	"\x11resolution_source\x18\a \x01(\tR\x10resolutionSource\"/\n" +
	"\x0ePendingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"D\n" +
	"\x0fPendingResponse\x121\n" +
	"\areviews\x18\x01 \x03(\v2\x17.cyber.guardrail.ReviewR\areviews\"l\n" +
	"\x0eResolveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove\"\x11\n" +
	"\x0fResolveResponse\"\xa1\x02\n" +
	"\x0fProtocolMessage\x12;\n" +
	"\apending\x18\x01 \x01(\v2\x1f.cyber.guardrail.PendingRequestH\x00R\apending\x12I\n" +
	"\x0epending_result\x18\x02 \x01(\v2 .cyber.guardrail.PendingResponseH\x00R\rpendingResult\x12;\n" +
	"\aresolve\x18\x03 \x01(\v2\x1f.cyber.guardrail.ResolveRequestH\x00R\aresolve\x12>\n" +
	"\bresolved\x18\x04 \x01(\v2 .cyber.guardrail.ResolveResponseH\x00R\bresolvedB\t\n" +
	"\amessage*X\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_RECORD\x10\x01\x12\x11\n" +
	"\rACTION_REVIEW\x10\x02\x12\x10\n" +
	"\fACTION_BLOCK\x10\x03*\xb0\x01\n" +
	"\vReviewState\x12\x1c\n" +
	"\x18REVIEW_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REVIEW_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15REVIEW_STATE_APPROVED\x10\x02\x12\x19\n" +
	"\x15REVIEW_STATE_REJECTED\x10\x03\x12\x18\n" +
	"\x14REVIEW_STATE_EXPIRED\x10\x04\x12\x19\n" +
	"\x15REVIEW_STATE_CANCELED\x10\x05B=Z;github.com/chainreactors/cyber/pkg/exts/guardrail;guardrailb\x06proto3"

var (
	file_types_guardrail_proto_rawDescOnce sync.Once
	file_types_guardrail_proto_rawDescData []byte
)

func file_types_guardrail_proto_rawDescGZIP() []byte {
	file_types_guardrail_proto_rawDescOnce.Do(func() {
		file_types_guardrail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_guardrail_proto_rawDesc), len(file_types_guardrail_proto_rawDesc)))
	})
	return file_types_guardrail_proto_rawDescData
}

var file_types_guardrail_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_guardrail_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_types_guardrail_proto_goTypes = []any{
	(Action)(0),                   // 0: cyber.guardrail.Action
	(ReviewState)(0),              // 1: cyber.guardrail.ReviewState
	(*Decision)(nil),              // 2: cyber.guardrail.Decision
	(*Review)(nil),                // 3: cyber.guardrail.Review
	(*PendingRequest)(nil),        // 4: cyber.guardrail.PendingRequest
	(*PendingResponse)(nil),       // 5: cyber.guardrail.PendingResponse
	(*ResolveRequest)(nil),        // 6: cyber.guardrail.ResolveRequest
	(*ResolveResponse)(nil),       // 7: cyber.guardrail.ResolveResponse
	(*ProtocolMessage)(nil),       // 8: cyber.guardrail.ProtocolMessage
	(*aop.ToolCall)(nil),          // 9: aop.ToolCall
	(*operation.Ref)(nil),         // 10: aop.operation.Ref
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_types_guardrail_proto_depIdxs = []int32{
	0,  // 0: cyber.guardrail.Decision.action:type_name -> cyber.guardrail.Action
	9,  // 1: cyber.guardrail.Review.call:type_name -> aop.ToolCall
	10, // 2: cyber.guardrail.Review.operation:type_name -> aop.operation.Ref
	2,  // 3: cyber.guardrail.Review.decision:type_name -> cyber.guardrail.Decision
	1,  // 4: cyber.guardrail.Review.state:type_name -> cyber.guardrail.ReviewState
	11, // 5: cyber.guardrail.Review.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 6: cyber.guardrail.PendingResponse.reviews:type_name -> cyber.guardrail.Review
	4,  // 7: cyber.guardrail.ProtocolMessage.pending:type_name -> cyber.guardrail.PendingRequest
	5,  // 8: cyber.guardrail.ProtocolMessage.pending_result:type_name -> cyber.guardrail.PendingResponse
	6,  // 9: cyber.guardrail.ProtocolMessage.resolve:type_name -> cyber.guardrail.ResolveRequest
	7,  // 10: cyber.guardrail.ProtocolMessage.resolved:type_name -> cyber.guardrail.ResolveResponse
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_types_guardrail_proto_init() }
func file_types_guardrail_proto_init() {
	if File_types_guardrail_proto != nil {
		return
	}
	file_types_guardrail_proto_msgTypes[6].OneofWrappers = []any{
		(*ProtocolMessage_Pending)(nil),
		(*ProtocolMessage_PendingResult)(nil),
		(*ProtocolMessage_Resolve)(nil),
		(*ProtocolMessage_Resolved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_guardrail_proto_rawDesc), len(file_types_guardrail_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_guardrail_proto_goTypes,
		DependencyIndexes: file_types_guardrail_proto_depIdxs,
		EnumInfos:         file_types_guardrail_proto_enumTypes,
		MessageInfos:      file_types_guardrail_proto_msgTypes,
	}.Build()
	File_types_guardrail_proto = out.File
	file_types_guardrail_proto_goTypes = nil
	file_types_guardrail_proto_depIdxs = nil
}
