// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: types/jev.proto

package jev

import (
	aop "github.com/chainreactors/cyber/aop"
	decision "github.com/chainreactors/cyber/core/decision"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          decision.ClaimType     `protobuf:"varint,2,opt,name=type,proto3,enum=decision.ClaimType" json:"type,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	SourceTaskId  string                 `protobuf:"bytes,5,opt,name=source_task_id,json=sourceTaskId,proto3" json:"source_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimDefinition) Reset() {
	*x = ClaimDefinition{}
	mi := &file_types_jev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDefinition) ProtoMessage() {}

func (x *ClaimDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDefinition.ProtoReflect.Descriptor instead.
func (*ClaimDefinition) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClaimDefinition) GetType() decision.ClaimType {
	if x != nil {
		return x.Type
	}
	return decision.ClaimType(0)
}

func (x *ClaimDefinition) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ClaimDefinition) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ClaimDefinition) GetSourceTaskId() string {
	if x != nil {
		return x.SourceTaskId
	}
	return ""
}

type ReflexDefinition struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	When              string                 `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	Decide            string                 `protobuf:"bytes,3,opt,name=decide,proto3" json:"decide,omitempty"`
	Observe           string                 `protobuf:"bytes,4,opt,name=observe,proto3" json:"observe,omitempty"`
	ClaimIds          []string               `protobuf:"bytes,5,rep,name=claim_ids,json=claimIds,proto3" json:"claim_ids,omitempty"`
	Readers           map[string]string      `protobuf:"bytes,6,rep,name=readers,proto3" json:"readers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Contracts         map[string]string      `protobuf:"bytes,7,rep,name=contracts,proto3" json:"contracts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ApiVersion        uint32                 `protobuf:"varint,8,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	QualificationJson string                 `protobuf:"bytes,9,opt,name=qualification_json,json=qualificationJson,proto3" json:"qualification_json,omitempty"`
	ManifestJson      string                 `protobuf:"bytes,10,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Blocker           string                 `protobuf:"bytes,11,opt,name=blocker,proto3" json:"blocker,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReflexDefinition) Reset() {
	*x = ReflexDefinition{}
	mi := &file_types_jev_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflexDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflexDefinition) ProtoMessage() {}

func (x *ReflexDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflexDefinition.ProtoReflect.Descriptor instead.
func (*ReflexDefinition) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{1}
}

func (x *ReflexDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReflexDefinition) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *ReflexDefinition) GetDecide() string {
	if x != nil {
		return x.Decide
	}
	return ""
}

func (x *ReflexDefinition) GetObserve() string {
	if x != nil {
		return x.Observe
	}
	return ""
}

func (x *ReflexDefinition) GetClaimIds() []string {
	if x != nil {
		return x.ClaimIds
	}
	return nil
}

func (x *ReflexDefinition) GetReaders() map[string]string {
	if x != nil {
		return x.Readers
	}
	return nil
}

func (x *ReflexDefinition) GetContracts() map[string]string {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *ReflexDefinition) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *ReflexDefinition) GetQualificationJson() string {
	if x != nil {
		return x.QualificationJson
	}
	return ""
}

func (x *ReflexDefinition) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *ReflexDefinition) GetBlocker() string {
	if x != nil {
		return x.Blocker
	}
	return ""
}

type Boundary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Boundary) Reset() {
	*x = Boundary{}
	mi := &file_types_jev_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boundary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boundary) ProtoMessage() {}

func (x *Boundary) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boundary.ProtoReflect.Descriptor instead.
func (*Boundary) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{2}
}

func (x *Boundary) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Observation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StateJson      string                 `protobuf:"bytes,1,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	CandidatesJson string                 `protobuf:"bytes,2,opt,name=candidates_json,json=candidatesJson,proto3" json:"candidates_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_types_jev_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{3}
}

func (x *Observation) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

func (x *Observation) GetCandidatesJson() string {
	if x != nil {
		return x.CandidatesJson
	}
	return ""
}

type DecisionRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RequestId     string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Purpose       string                     `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Claims        map[string]*decision.Claim `protobuf:"bytes,3,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_types_jev_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecisionRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *DecisionRequest) GetClaims() map[string]*decision.Claim {
	if x != nil {
		return x.Claims
	}
	return nil
}

type DecisionResult struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	RequestId     string                          `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Purpose       string                          `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Evaluations   map[string]*decision.Evaluation `protobuf:"bytes,3,rep,name=evaluations,proto3" json:"evaluations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ElapsedMs     int64                           `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	Error         string                          `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Usage         *aop.TokenUsage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResult) Reset() {
	*x = DecisionResult{}
	mi := &file_types_jev_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResult) ProtoMessage() {}

func (x *DecisionResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResult.ProtoReflect.Descriptor instead.
func (*DecisionResult) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{5}
}

func (x *DecisionResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecisionResult) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *DecisionResult) GetEvaluations() map[string]*decision.Evaluation {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

func (x *DecisionResult) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *DecisionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DecisionResult) GetUsage() *aop.TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Takeover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *ReflexDefinition      `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Takeover) Reset() {
	*x = Takeover{}
	mi := &file_types_jev_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Takeover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Takeover) ProtoMessage() {}

func (x *Takeover) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Takeover.ProtoReflect.Descriptor instead.
func (*Takeover) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{6}
}

func (x *Takeover) GetDefinition() *ReflexDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type Dispatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *aop.ToolCall          `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Read          bool                   `protobuf:"varint,3,opt,name=read,proto3" json:"read,omitempty"`
	EffectId      string                 `protobuf:"bytes,4,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	StepId        string                 `protobuf:"bytes,5,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Occurrence    uint32                 `protobuf:"varint,6,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dispatch) Reset() {
	*x = Dispatch{}
	mi := &file_types_jev_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispatch) ProtoMessage() {}

func (x *Dispatch) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispatch.ProtoReflect.Descriptor instead.
func (*Dispatch) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{7}
}

func (x *Dispatch) GetCall() *aop.ToolCall {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *Dispatch) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *Dispatch) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Dispatch) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *Dispatch) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *Dispatch) GetOccurrence() uint32 {
	if x != nil {
		return x.Occurrence
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *aop.ToolResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,2,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_types_jev_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{8}
}

func (x *Result) GetResult() *aop.ToolResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Result) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type Handoff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	EffectsJson   string                 `protobuf:"bytes,4,opt,name=effects_json,json=effectsJson,proto3" json:"effects_json,omitempty"`
	ResultJson    string                 `protobuf:"bytes,5,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handoff) Reset() {
	*x = Handoff{}
	mi := &file_types_jev_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handoff) ProtoMessage() {}

func (x *Handoff) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handoff.ProtoReflect.Descriptor instead.
func (*Handoff) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{9}
}

func (x *Handoff) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Handoff) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Handoff) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Handoff) GetEffectsJson() string {
	if x != nil {
		return x.EffectsJson
	}
	return ""
}

func (x *Handoff) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type Generation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Output          string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ElapsedMs       int64                  `protobuf:"varint,5,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	Usage           *aop.TokenUsage        `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	RequestId       string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Attempt         uint32                 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ErrorStage      string                 `protobuf:"bytes,9,opt,name=error_stage,json=errorStage,proto3" json:"error_stage,omitempty"`
	RequestedEffort string                 `protobuf:"bytes,10,opt,name=requested_effort,json=requestedEffort,proto3" json:"requested_effort,omitempty"`
	ParentRequestId string                 `protobuf:"bytes,11,opt,name=parent_request_id,json=parentRequestId,proto3" json:"parent_request_id,omitempty"`
	Phase           string                 `protobuf:"bytes,12,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_types_jev_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{10}
}

func (x *Generation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Generation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Generation) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Generation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Generation) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *Generation) GetUsage() *aop.TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Generation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Generation) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Generation) GetErrorStage() string {
	if x != nil {
		return x.ErrorStage
	}
	return ""
}

func (x *Generation) GetRequestedEffort() string {
	if x != nil {
		return x.RequestedEffort
	}
	return ""
}

func (x *Generation) GetParentRequestId() string {
	if x != nil {
		return x.ParentRequestId
	}
	return ""
}

func (x *Generation) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type LibraryChange struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	State            string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Claim            *ClaimDefinition       `protobuf:"bytes,2,opt,name=claim,proto3" json:"claim,omitempty"`
	Reflex           *ReflexDefinition      `protobuf:"bytes,3,opt,name=reflex,proto3" json:"reflex,omitempty"`
	ReplacedReflexId string                 `protobuf:"bytes,4,opt,name=replaced_reflex_id,json=replacedReflexId,proto3" json:"replaced_reflex_id,omitempty"`
	Reason           string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ErrorStage       string                 `protobuf:"bytes,6,opt,name=error_stage,json=errorStage,proto3" json:"error_stage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LibraryChange) Reset() {
	*x = LibraryChange{}
	mi := &file_types_jev_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryChange) ProtoMessage() {}

func (x *LibraryChange) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryChange.ProtoReflect.Descriptor instead.
func (*LibraryChange) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{11}
}

func (x *LibraryChange) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LibraryChange) GetClaim() *ClaimDefinition {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *LibraryChange) GetReflex() *ReflexDefinition {
	if x != nil {
		return x.Reflex
	}
	return nil
}

func (x *LibraryChange) GetReplacedReflexId() string {
	if x != nil {
		return x.ReplacedReflexId
	}
	return ""
}

func (x *LibraryChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LibraryChange) GetErrorStage() string {
	if x != nil {
		return x.ErrorStage
	}
	return ""
}

// Runtime and asynchronous compilation share source correlation. Background
// events never imply that the source turn is still running.
type RuntimeEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SegmentId         string                 `protobuf:"bytes,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	PreviousSegmentId string                 `protobuf:"bytes,3,opt,name=previous_segment_id,json=previousSegmentId,proto3" json:"previous_segment_id,omitempty"`
	Step              uint32                 `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	ReflexId          string                 `protobuf:"bytes,5,opt,name=reflex_id,json=reflexId,proto3" json:"reflex_id,omitempty"`
	CallId            string                 `protobuf:"bytes,6,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Background        bool                   `protobuf:"varint,7,opt,name=background,proto3" json:"background,omitempty"`
	BoundaryId        string                 `protobuf:"bytes,8,opt,name=boundary_id,json=boundaryId,proto3" json:"boundary_id,omitempty"`
	ClaimId           string                 `protobuf:"bytes,9,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RuntimeEvent_Boundary
	//	*RuntimeEvent_Observation
	//	*RuntimeEvent_DecisionRequest
	//	*RuntimeEvent_DecisionResult
	//	*RuntimeEvent_Takeover
	//	*RuntimeEvent_Dispatch
	//	*RuntimeEvent_Result
	//	*RuntimeEvent_Handoff
	//	*RuntimeEvent_Generation
	//	*RuntimeEvent_LibraryChange
	Payload       isRuntimeEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEvent) Reset() {
	*x = RuntimeEvent{}
	mi := &file_types_jev_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent) ProtoMessage() {}

func (x *RuntimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent.ProtoReflect.Descriptor instead.
func (*RuntimeEvent) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{12}
}

func (x *RuntimeEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RuntimeEvent) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *RuntimeEvent) GetPreviousSegmentId() string {
	if x != nil {
		return x.PreviousSegmentId
	}
	return ""
}

func (x *RuntimeEvent) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *RuntimeEvent) GetReflexId() string {
	if x != nil {
		return x.ReflexId
	}
	return ""
}

func (x *RuntimeEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *RuntimeEvent) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

func (x *RuntimeEvent) GetBoundaryId() string {
	if x != nil {
		return x.BoundaryId
	}
	return ""
}

func (x *RuntimeEvent) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *RuntimeEvent) GetPayload() isRuntimeEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RuntimeEvent) GetBoundary() *Boundary {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_Boundary); ok {
			return x.Boundary
		}
	}
	return nil
}

func (x *RuntimeEvent) GetObservation() *Observation {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_Observation); ok {
			return x.Observation
		}
	}
	return nil
}

func (x *RuntimeEvent) GetDecisionRequest() *DecisionRequest {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_DecisionRequest); ok {
			return x.DecisionRequest
		}
	}
	return nil
}

func (x *RuntimeEvent) GetDecisionResult() *DecisionResult {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_DecisionResult); ok {
			return x.DecisionResult
		}
	}
	return nil
}

func (x *RuntimeEvent) GetTakeover() *Takeover {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_Takeover); ok {
			return x.Takeover
		}
	}
	return nil
}

func (x *RuntimeEvent) GetDispatch() *Dispatch {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

func (x *RuntimeEvent) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *RuntimeEvent) GetHandoff() *Handoff {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_Handoff); ok {
			return x.Handoff
		}
	}
	return nil
}

func (x *RuntimeEvent) GetGeneration() *Generation {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_Generation); ok {
			return x.Generation
		}
	}
	return nil
}

func (x *RuntimeEvent) GetLibraryChange() *LibraryChange {
	if x != nil {
		if x, ok := x.Payload.(*RuntimeEvent_LibraryChange); ok {
			return x.LibraryChange
		}
	}
	return nil
}

type isRuntimeEvent_Payload interface {
	isRuntimeEvent_Payload()
}

type RuntimeEvent_Boundary struct {
	Boundary *Boundary `protobuf:"bytes,10,opt,name=boundary,proto3,oneof"`
}

type RuntimeEvent_Observation struct {
	Observation *Observation `protobuf:"bytes,11,opt,name=observation,proto3,oneof"`
}

type RuntimeEvent_DecisionRequest struct {
	DecisionRequest *DecisionRequest `protobuf:"bytes,12,opt,name=decision_request,json=decisionRequest,proto3,oneof"`
}

type RuntimeEvent_DecisionResult struct {
	DecisionResult *DecisionResult `protobuf:"bytes,13,opt,name=decision_result,json=decisionResult,proto3,oneof"`
}

type RuntimeEvent_Takeover struct {
	Takeover *Takeover `protobuf:"bytes,14,opt,name=takeover,proto3,oneof"`
}

type RuntimeEvent_Dispatch struct {
	Dispatch *Dispatch `protobuf:"bytes,15,opt,name=dispatch,proto3,oneof"`
}

type RuntimeEvent_Result struct {
	Result *Result `protobuf:"bytes,16,opt,name=result,proto3,oneof"`
}

type RuntimeEvent_Handoff struct {
	Handoff *Handoff `protobuf:"bytes,17,opt,name=handoff,proto3,oneof"`
}

type RuntimeEvent_Generation struct {
	Generation *Generation `protobuf:"bytes,18,opt,name=generation,proto3,oneof"`
}

type RuntimeEvent_LibraryChange struct {
	LibraryChange *LibraryChange `protobuf:"bytes,19,opt,name=library_change,json=libraryChange,proto3,oneof"`
}

func (*RuntimeEvent_Boundary) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_Observation) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_DecisionRequest) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_DecisionResult) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_Takeover) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_Dispatch) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_Result) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_Handoff) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_Generation) isRuntimeEvent_Payload() {}

func (*RuntimeEvent_LibraryChange) isRuntimeEvent_Payload() {}

type GetLibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryRequest) Reset() {
	*x = GetLibraryRequest{}
	mi := &file_types_jev_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryRequest) ProtoMessage() {}

func (x *GetLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryRequest.ProtoReflect.Descriptor instead.
func (*GetLibraryRequest) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{13}
}

func (x *GetLibraryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WaitIdleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitIdleRequest) Reset() {
	*x = WaitIdleRequest{}
	mi := &file_types_jev_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitIdleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitIdleRequest) ProtoMessage() {}

func (x *WaitIdleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitIdleRequest.ProtoReflect.Descriptor instead.
func (*WaitIdleRequest) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{14}
}

func (x *WaitIdleRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WaitIdleRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitIdleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settled       bool                   `protobuf:"varint,1,opt,name=settled,proto3" json:"settled,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitIdleResponse) Reset() {
	*x = WaitIdleResponse{}
	mi := &file_types_jev_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitIdleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitIdleResponse) ProtoMessage() {}

func (x *WaitIdleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitIdleResponse.ProtoReflect.Descriptor instead.
func (*WaitIdleResponse) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{15}
}

func (x *WaitIdleResponse) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

func (x *WaitIdleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetLibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Revision      string                 `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Claims        []*ClaimDefinition     `protobuf:"bytes,5,rep,name=claims,proto3" json:"claims,omitempty"`
	Reflexes      []*ReflexDefinition    `protobuf:"bytes,6,rep,name=reflexes,proto3" json:"reflexes,omitempty"`
	Candidates    []*ReflexDefinition    `protobuf:"bytes,7,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Learning      string                 `protobuf:"bytes,8,opt,name=learning,proto3" json:"learning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryResponse) Reset() {
	*x = GetLibraryResponse{}
	mi := &file_types_jev_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryResponse) ProtoMessage() {}

func (x *GetLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryResponse.ProtoReflect.Descriptor instead.
func (*GetLibraryResponse) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{16}
}

func (x *GetLibraryResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetLibraryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetLibraryResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GetLibraryResponse) GetClaims() []*ClaimDefinition {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *GetLibraryResponse) GetReflexes() []*ReflexDefinition {
	if x != nil {
		return x.Reflexes
	}
	return nil
}

func (x *GetLibraryResponse) GetCandidates() []*ReflexDefinition {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GetLibraryResponse) GetLearning() string {
	if x != nil {
		return x.Learning
	}
	return ""
}

type ProtocolMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ProtocolMessage_Request
	//	*ProtocolMessage_Library
	//	*ProtocolMessage_WaitIdle
	//	*ProtocolMessage_Idle
	Message       isProtocolMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessage) Reset() {
	*x = ProtocolMessage{}
	mi := &file_types_jev_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessage) ProtoMessage() {}

func (x *ProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_jev_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessage.ProtoReflect.Descriptor instead.
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return file_types_jev_proto_rawDescGZIP(), []int{17}
}

func (x *ProtocolMessage) GetMessage() isProtocolMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProtocolMessage) GetRequest() *GetLibraryRequest {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ProtocolMessage) GetLibrary() *GetLibraryResponse {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Library); ok {
			return x.Library
		}
	}
	return nil
}

func (x *ProtocolMessage) GetWaitIdle() *WaitIdleRequest {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_WaitIdle); ok {
			return x.WaitIdle
		}
	}
	return nil
}

func (x *ProtocolMessage) GetIdle() *WaitIdleResponse {
	if x != nil {
		if x, ok := x.Message.(*ProtocolMessage_Idle); ok {
			return x.Idle
		}
	}
	return nil
}

type isProtocolMessage_Message interface {
	isProtocolMessage_Message()
}

type ProtocolMessage_Request struct {
	Request *GetLibraryRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type ProtocolMessage_Library struct {
	Library *GetLibraryResponse `protobuf:"bytes,2,opt,name=library,proto3,oneof"`
}

type ProtocolMessage_WaitIdle struct {
	WaitIdle *WaitIdleRequest `protobuf:"bytes,3,opt,name=wait_idle,json=waitIdle,proto3,oneof"`
}

type ProtocolMessage_Idle struct {
	Idle *WaitIdleResponse `protobuf:"bytes,4,opt,name=idle,proto3,oneof"`
}

func (*ProtocolMessage_Request) isProtocolMessage_Message() {}

func (*ProtocolMessage_Library) isProtocolMessage_Message() {}

func (*ProtocolMessage_WaitIdle) isProtocolMessage_Message() {}

func (*ProtocolMessage_Idle) isProtocolMessage_Message() {}

var File_types_jev_proto protoreflect.FileDescriptor

const file_types_jev_proto_rawDesc = "" +
	"\n" +
	"\x0ftypes/jev.proto\x12\tcyber.jev\x1a\x11aop/content.proto\x1a\x0faop/event.proto\x1a\x14decision/claim.proto\"\xb0\x01\n" +
	"\x0fClaimDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.decision.ClaimTypeR\x04type\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12$\n" +
	"\x0esource_task_id\x18\x05 \x01(\tR\fsourceTaskIdJ\x04\b\x06\x10\aJ\x04\b\a\x10\b\"\x9c\x04\n" +
	"\x10ReflexDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04when\x18\x02 \x01(\tR\x04when\x12\x16\n" +
	"\x06decide\x18\x03 \x01(\tR\x06decide\x12\x18\n" +
	"\aobserve\x18\x04 \x01(\tR\aobserve\x12\x1b\n" +
	"\tclaim_ids\x18\x05 \x03(\tR\bclaimIds\x12B\n" +
	"\areaders\x18\x06 \x03(\v2(.cyber.jev.ReflexDefinition.ReadersEntryR\areaders\x12H\n" +
	"\tcontracts\x18\a \x03(\v2*.cyber.jev.ReflexDefinition.ContractsEntryR\tcontracts\x12\x1f\n" +
	"\vapi_version\x18\b \x01(\rR\n" +
	"apiVersion\x12-\n" +
	"\x12qualification_json\x18\t \x01(\tR\x11qualificationJson\x12#\n" +
	"\rmanifest_json\x18\n" +
	" \x01(\tR\fmanifestJson\x12\x18\n" +
	"\ablocker\x18\v \x01(\tR\ablocker\x1a:\n" +
	"\fReadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eContractsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\bBoundary\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"U\n" +
	"\vObservation\x12\x1d\n" +
	"\n" +
	"state_json\x18\x01 \x01(\tR\tstateJson\x12'\n" +
	"\x0fcandidates_json\x18\x02 \x01(\tR\x0ecandidatesJson\"\xd6\x01\n" +
	"\x0fDecisionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12>\n" +
	"\x06claims\x18\x03 \x03(\v2&.cyber.jev.DecisionRequest.ClaimsEntryR\x06claims\x1aJ\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.decision.ClaimR\x05value:\x028\x01\"\xc9\x02\n" +
	"\x0eDecisionResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12L\n" +
	"\vevaluations\x18\x03 \x03(\v2*.cyber.jev.DecisionResult.EvaluationsEntryR\vevaluations\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12%\n" +
	"\x05usage\x18\x06 \x01(\v2\x0f.aop.TokenUsageR\x05usage\x1aT\n" +
	"\x10EvaluationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.decision.EvaluationR\x05value:\x028\x01\"G\n" +
	"\bTakeover\x12;\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x1b.cyber.jev.ReflexDefinitionR\n" +
	"definition\"\xba\x01\n" +
	"\bDispatch\x12!\n" +
	"\x04call\x18\x01 \x01(\v2\r.aop.ToolCallR\x04call\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12\x12\n" +
	"\x04read\x18\x03 \x01(\bR\x04read\x12\x1b\n" +
	"\teffect_id\x18\x04 \x01(\tR\beffectId\x12\x17\n" +
	"\astep_id\x18\x05 \x01(\tR\x06stepId\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x06 \x01(\rR\n" +
	"occurrence\"P\n" +
	"\x06Result\x12'\n" +
	"\x06result\x18\x01 \x01(\v2\x0f.aop.ToolResultR\x06result\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x02 \x01(\x03R\telapsedMs\"\x91\x01\n" +
	"\aHandoff\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12!\n" +
	"\feffects_json\x18\x04 \x01(\tR\veffectsJson\x12\x1f\n" +
	"\vresult_json\x18\x05 \x01(\tR\n" +
	"resultJson\"\xf1\x02\n" +
	"\n" +
	"Generation\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x05 \x01(\x03R\telapsedMs\x12%\n" +
	"\x05usage\x18\x06 \x01(\v2\x0f.aop.TokenUsageR\x05usage\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x18\n" +
	"\aattempt\x18\b \x01(\rR\aattempt\x12\x1f\n" +
	"\verror_stage\x18\t \x01(\tR\n" +
	"errorStage\x12)\n" +
	"\x10requested_effort\x18\n" +
	" \x01(\tR\x0frequestedEffort\x12*\n" +
	"\x11parent_request_id\x18\v \x01(\tR\x0fparentRequestId\x12\x14\n" +
	"\x05phase\x18\f \x01(\tR\x05phase\"\xf3\x01\n" +
	"\rLibraryChange\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x120\n" +
	"\x05claim\x18\x02 \x01(\v2\x1a.cyber.jev.ClaimDefinitionR\x05claim\x123\n" +
	"\x06reflex\x18\x03 \x01(\v2\x1b.cyber.jev.ReflexDefinitionR\x06reflex\x12,\n" +
	"\x12replaced_reflex_id\x18\x04 \x01(\tR\x10replacedReflexId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1f\n" +
	"\verror_stage\x18\x06 \x01(\tR\n" +
	"errorStage\"\xe4\x06\n" +
	"\fRuntimeEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\tR\tsegmentId\x12.\n" +
	"\x13previous_segment_id\x18\x03 \x01(\tR\x11previousSegmentId\x12\x12\n" +
	"\x04step\x18\x04 \x01(\rR\x04step\x12\x1b\n" +
	"\treflex_id\x18\x05 \x01(\tR\breflexId\x12\x17\n" +
	"\acall_id\x18\x06 \x01(\tR\x06callId\x12\x1e\n" +
	"\n" +
	"background\x18\a \x01(\bR\n" +
	"background\x12\x1f\n" +
	"\vboundary_id\x18\b \x01(\tR\n" +
	"boundaryId\x12\x19\n" +
	"\bclaim_id\x18\t \x01(\tR\aclaimId\x121\n" +
	"\bboundary\x18\n" +
	" \x01(\v2\x13.cyber.jev.BoundaryH\x00R\bboundary\x12:\n" +
	"\vobservation\x18\v \x01(\v2\x16.cyber.jev.ObservationH\x00R\vobservation\x12G\n" +
	"\x10decision_request\x18\f \x01(\v2\x1a.cyber.jev.DecisionRequestH\x00R\x0fdecisionRequest\x12D\n" +
	"\x0fdecision_result\x18\r \x01(\v2\x19.cyber.jev.DecisionResultH\x00R\x0edecisionResult\x121\n" +
	"\btakeover\x18\x0e \x01(\v2\x13.cyber.jev.TakeoverH\x00R\btakeover\x121\n" +
	"\bdispatch\x18\x0f \x01(\v2\x13.cyber.jev.DispatchH\x00R\bdispatch\x12+\n" +
	"\x06result\x18\x10 \x01(\v2\x11.cyber.jev.ResultH\x00R\x06result\x12.\n" +
	"\ahandoff\x18\x11 \x01(\v2\x12.cyber.jev.HandoffH\x00R\ahandoff\x127\n" +
	"\n" +
	"generation\x18\x12 \x01(\v2\x15.cyber.jev.GenerationH\x00R\n" +
	"generation\x12A\n" +
	"\x0elibrary_change\x18\x13 \x01(\v2\x18.cyber.jev.LibraryChangeH\x00R\rlibraryChangeB\t\n" +
	"\apayload\"2\n" +
	"\x11GetLibraryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"O\n" +
	"\x0fWaitIdleRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"B\n" +
	"\x10WaitIdleResponse\x12\x18\n" +
	"\asettled\x18\x01 \x01(\bR\asettled\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa8\x02\n" +
	"\x12GetLibraryResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\tR\brevision\x122\n" +
	"\x06claims\x18\x05 \x03(\v2\x1a.cyber.jev.ClaimDefinitionR\x06claims\x127\n" +
	"\breflexes\x18\x06 \x03(\v2\x1b.cyber.jev.ReflexDefinitionR\breflexes\x12;\n" +
	"\n" +
	"candidates\x18\a \x03(\v2\x1b.cyber.jev.ReflexDefinitionR\n" +
	"candidates\x12\x1a\n" +
	"\blearning\x18\b \x01(\tR\blearningJ\x04\b\x03\x10\x04\"\xff\x01\n" +
	"\x0fProtocolMessage\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1c.cyber.jev.GetLibraryRequestH\x00R\arequest\x129\n" +
	"\alibrary\x18\x02 \x01(\v2\x1d.cyber.jev.GetLibraryResponseH\x00R\alibrary\x129\n" +
	"\twait_idle\x18\x03 \x01(\v2\x1a.cyber.jev.WaitIdleRequestH\x00R\bwaitIdle\x121\n" +
	"\x04idle\x18\x04 \x01(\v2\x1b.cyber.jev.WaitIdleResponseH\x00R\x04idleB\t\n" +
	"\amessageB-Z+github.com/chainreactors/cyber/exts/jev;jevb\x06proto3"

var (
	file_types_jev_proto_rawDescOnce sync.Once
	file_types_jev_proto_rawDescData []byte
)

func file_types_jev_proto_rawDescGZIP() []byte {
	file_types_jev_proto_rawDescOnce.Do(func() {
		file_types_jev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_jev_proto_rawDesc), len(file_types_jev_proto_rawDesc)))
	})
	return file_types_jev_proto_rawDescData
}

var file_types_jev_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_types_jev_proto_goTypes = []any{
	(*ClaimDefinition)(nil),     // 0: cyber.jev.ClaimDefinition
	(*ReflexDefinition)(nil),    // 1: cyber.jev.ReflexDefinition
	(*Boundary)(nil),            // 2: cyber.jev.Boundary
	(*Observation)(nil),         // 3: cyber.jev.Observation
	(*DecisionRequest)(nil),     // 4: cyber.jev.DecisionRequest
	(*DecisionResult)(nil),      // 5: cyber.jev.DecisionResult
	(*Takeover)(nil),            // 6: cyber.jev.Takeover
	(*Dispatch)(nil),            // 7: cyber.jev.Dispatch
	(*Result)(nil),              // 8: cyber.jev.Result
	(*Handoff)(nil),             // 9: cyber.jev.Handoff
	(*Generation)(nil),          // 10: cyber.jev.Generation
	(*LibraryChange)(nil),       // 11: cyber.jev.LibraryChange
	(*RuntimeEvent)(nil),        // 12: cyber.jev.RuntimeEvent
	(*GetLibraryRequest)(nil),   // 13: cyber.jev.GetLibraryRequest
	(*WaitIdleRequest)(nil),     // 14: cyber.jev.WaitIdleRequest
	(*WaitIdleResponse)(nil),    // 15: cyber.jev.WaitIdleResponse
	(*GetLibraryResponse)(nil),  // 16: cyber.jev.GetLibraryResponse
	(*ProtocolMessage)(nil),     // 17: cyber.jev.ProtocolMessage
	nil,                         // 18: cyber.jev.ReflexDefinition.ReadersEntry
	nil,                         // 19: cyber.jev.ReflexDefinition.ContractsEntry
	nil,                         // 20: cyber.jev.DecisionRequest.ClaimsEntry
	nil,                         // 21: cyber.jev.DecisionResult.EvaluationsEntry
	(decision.ClaimType)(0),     // 22: decision.ClaimType
	(*aop.TokenUsage)(nil),      // 23: aop.TokenUsage
	(*aop.ToolCall)(nil),        // 24: aop.ToolCall
	(*aop.ToolResult)(nil),      // 25: aop.ToolResult
	(*decision.Claim)(nil),      // 26: decision.Claim
	(*decision.Evaluation)(nil), // 27: decision.Evaluation
}
var file_types_jev_proto_depIdxs = []int32{
	22, // 0: cyber.jev.ClaimDefinition.type:type_name -> decision.ClaimType
	18, // 1: cyber.jev.ReflexDefinition.readers:type_name -> cyber.jev.ReflexDefinition.ReadersEntry
	19, // 2: cyber.jev.ReflexDefinition.contracts:type_name -> cyber.jev.ReflexDefinition.ContractsEntry
	20, // 3: cyber.jev.DecisionRequest.claims:type_name -> cyber.jev.DecisionRequest.ClaimsEntry
	21, // 4: cyber.jev.DecisionResult.evaluations:type_name -> cyber.jev.DecisionResult.EvaluationsEntry
	23, // 5: cyber.jev.DecisionResult.usage:type_name -> aop.TokenUsage
	1,  // 6: cyber.jev.Takeover.definition:type_name -> cyber.jev.ReflexDefinition
	24, // 7: cyber.jev.Dispatch.call:type_name -> aop.ToolCall
	25, // 8: cyber.jev.Result.result:type_name -> aop.ToolResult
	23, // 9: cyber.jev.Generation.usage:type_name -> aop.TokenUsage
	0,  // 10: cyber.jev.LibraryChange.claim:type_name -> cyber.jev.ClaimDefinition
	1,  // 11: cyber.jev.LibraryChange.reflex:type_name -> cyber.jev.ReflexDefinition
	2,  // 12: cyber.jev.RuntimeEvent.boundary:type_name -> cyber.jev.Boundary
	3,  // 13: cyber.jev.RuntimeEvent.observation:type_name -> cyber.jev.Observation
	4,  // 14: cyber.jev.RuntimeEvent.decision_request:type_name -> cyber.jev.DecisionRequest
	5,  // 15: cyber.jev.RuntimeEvent.decision_result:type_name -> cyber.jev.DecisionResult
	6,  // 16: cyber.jev.RuntimeEvent.takeover:type_name -> cyber.jev.Takeover
	7,  // 17: cyber.jev.RuntimeEvent.dispatch:type_name -> cyber.jev.Dispatch
	8,  // 18: cyber.jev.RuntimeEvent.result:type_name -> cyber.jev.Result
	9,  // 19: cyber.jev.RuntimeEvent.handoff:type_name -> cyber.jev.Handoff
	10, // 20: cyber.jev.RuntimeEvent.generation:type_name -> cyber.jev.Generation
	11, // 21: cyber.jev.RuntimeEvent.library_change:type_name -> cyber.jev.LibraryChange
	0,  // 22: cyber.jev.GetLibraryResponse.claims:type_name -> cyber.jev.ClaimDefinition
	1,  // 23: cyber.jev.GetLibraryResponse.reflexes:type_name -> cyber.jev.ReflexDefinition
	1,  // 24: cyber.jev.GetLibraryResponse.candidates:type_name -> cyber.jev.ReflexDefinition
	13, // 25: cyber.jev.ProtocolMessage.request:type_name -> cyber.jev.GetLibraryRequest
	16, // 26: cyber.jev.ProtocolMessage.library:type_name -> cyber.jev.GetLibraryResponse
	14, // 27: cyber.jev.ProtocolMessage.wait_idle:type_name -> cyber.jev.WaitIdleRequest
	15, // 28: cyber.jev.ProtocolMessage.idle:type_name -> cyber.jev.WaitIdleResponse
	26, // 29: cyber.jev.DecisionRequest.ClaimsEntry.value:type_name -> decision.Claim
	27, // 30: cyber.jev.DecisionResult.EvaluationsEntry.value:type_name -> decision.Evaluation
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_types_jev_proto_init() }
func file_types_jev_proto_init() {
	if File_types_jev_proto != nil {
		return
	}
	file_types_jev_proto_msgTypes[12].OneofWrappers = []any{
		(*RuntimeEvent_Boundary)(nil),
		(*RuntimeEvent_Observation)(nil),
		(*RuntimeEvent_DecisionRequest)(nil),
		(*RuntimeEvent_DecisionResult)(nil),
		(*RuntimeEvent_Takeover)(nil),
		(*RuntimeEvent_Dispatch)(nil),
		(*RuntimeEvent_Result)(nil),
		(*RuntimeEvent_Handoff)(nil),
		(*RuntimeEvent_Generation)(nil),
		(*RuntimeEvent_LibraryChange)(nil),
	}
	file_types_jev_proto_msgTypes[17].OneofWrappers = []any{
		(*ProtocolMessage_Request)(nil),
		(*ProtocolMessage_Library)(nil),
		(*ProtocolMessage_WaitIdle)(nil),
		(*ProtocolMessage_Idle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_jev_proto_rawDesc), len(file_types_jev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_jev_proto_goTypes,
		DependencyIndexes: file_types_jev_proto_depIdxs,
		MessageInfos:      file_types_jev_proto_msgTypes,
	}.Build()
	File_types_jev_proto = out.File
	file_types_jev_proto_goTypes = nil
	file_types_jev_proto_depIdxs = nil
}
